CREATE TABLE client
(
    client_id    INTEGER     NOT NULL,
    firstname    VARCHAR(50) NOT NULL,
    lastname     VARCHAR(50) NOT NULL,
    age          INTEGER,
    nr_pers      INTEGER,
    checkin      VARCHAR(255),
    checkout     VARCHAR(255),
    phone_number VARCHAR(50),
    email        VARCHAR(50),
    hotel_id     INTEGER,
    CONSTRAINT pk_client PRIMARY KEY (client_id)
);

CREATE TABLE hotel
(
    hotel_id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    hotel_address VARCHAR(100)                             NOT NULL,
    hotel_city    VARCHAR(100)                             NOT NULL,
    hotel_country VARCHAR(100)                             NOT NULL,
    hotel_phone   VARCHAR(50)                              NOT NULL,
    hotel_email   VARCHAR(100)                             NOT NULL,
    CONSTRAINT pk_hotel PRIMARY KEY (hotel_id)
);

CREATE TABLE room
(
    id_room       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    floor         INTEGER                                  NOT NULL,
    number        INTEGER                                  NOT NULL,
    price         INTEGER                                  NOT NULL,
    beds          INTEGER                                  NOT NULL,
    reserved      BOOLEAN                                  NOT NULL,
    id_rooms_type INTEGER,
    CONSTRAINT pk_room PRIMARY KEY (id_room)
);

CREATE TABLE rooms_type
(
    id_rooms_type INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    current_type  VARCHAR(255)                             NOT NULL,
    id_room       INTEGER,
    hotel_id      INTEGER                                  NOT NULL,
    CONSTRAINT pk_rooms_type PRIMARY KEY (id_rooms_type)
);

ALTER TABLE hotel
    ADD CONSTRAINT uc_hotel_hotelphone UNIQUE (hotel_phone);

ALTER TABLE room
    ADD CONSTRAINT uc_room_number UNIQUE (number);

ALTER TABLE client
    ADD CONSTRAINT FK_CLIENT_ON_HOTEL FOREIGN KEY (hotel_id) REFERENCES hotel (hotel_id);

ALTER TABLE rooms_type
    ADD CONSTRAINT FK_ROOMS_TYPE_ON_HOTEL FOREIGN KEY (hotel_id) REFERENCES hotel (hotel_id);

ALTER TABLE rooms_type
    ADD CONSTRAINT FK_ROOMS_TYPE_ON_ID_ROOM FOREIGN KEY (id_room) REFERENCES room (id_room);

ALTER TABLE room
    ADD CONSTRAINT FK_ROOM_ON_ID_ROOMS_TYPE FOREIGN KEY (id_rooms_type) REFERENCES rooms_type (id_rooms_type);