create schema hotel_schema;

CREATE TABLE hotel_schema.client
(
    client_id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client_first_name   VARCHAR(50)                              NOT NULL,
    client_last_name    VARCHAR(50)                              NOT NULL,
    client_age          INTEGER                                  NOT NULL,
    client_nr_persons   INTEGER                                  NOT NULL,
    client_check_in     TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    client_check_out    TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    client_phone_number VARCHAR(50)                              NOT NULL,
    client_email        VARCHAR(50)                              NOT NULL,
    hotel_id            INTEGER,
    CONSTRAINT pk_client PRIMARY KEY (client_id)
);

CREATE TABLE hotel_schema.hotel
(
    hotel_id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    hotel_address VARCHAR(100)                             NOT NULL,
    hotel_city    VARCHAR(100)                             NOT NULL,
    hotel_country VARCHAR(100)                             NOT NULL,
    hotel_phone   VARCHAR(50)                              NOT NULL,
    hotel_email   VARCHAR(100)                             NOT NULL,
    CONSTRAINT pk_hotel PRIMARY KEY (hotel_id)
);

CREATE TABLE hotel_schema.room
(
    room_id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    room_floor    INTEGER                                  NOT NULL,
    room_number   INTEGER                                  NOT NULL,
    room_price    INTEGER                                  NOT NULL,
    room_beds     INTEGER                                  NOT NULL,
    room_reserved BOOLEAN                                  NOT NULL,
    rooms_type_id INTEGER,
    hotel_id      INTEGER,
    CONSTRAINT pk_room PRIMARY KEY (room_id)
);

CREATE TABLE hotel_schema.rooms_type
(
    rooms_type_id  INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    room_type_enum VARCHAR(255),
    CONSTRAINT pk_rooms_type PRIMARY KEY (rooms_type_id)
);

ALTER TABLE hotel_schema.hotel
    ADD CONSTRAINT uc_hotel_hotel_phone UNIQUE (hotel_phone);

ALTER TABLE hotel_schema.room
    ADD CONSTRAINT uc_room_room_number UNIQUE (room_number);

ALTER TABLE hotel_schema.client
    ADD CONSTRAINT FK_CLIENT_ON_HOTEL FOREIGN KEY (hotel_id) REFERENCES hotel_schema.hotel (hotel_id);

ALTER TABLE hotel_schema.room
    ADD CONSTRAINT FK_ROOM_ON_HOTEL FOREIGN KEY (hotel_id) REFERENCES hotel_schema.hotel (hotel_id);

ALTER TABLE hotel_schema.room
    ADD CONSTRAINT FK_ROOM_ON_ROOMS_TYPE FOREIGN KEY (rooms_type_id) REFERENCES hotel_schema.rooms_type (rooms_type_id);